version: "3"

services:
  flextesa:
    image: "tqtezos/flextesa:20201214"
    command: delphibox start 
    ports:
      - "8732:20000"
    environment:
      - block_time=1
    volumes:
      - ./tezos-client.config.json:/root/.tezos-client/config

