name: dapp
on:
  push:
    branches:
      - main
    paths:
      - 'packages/dapp/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-18.04
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --prod
      - name: Download deployments artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: contracts.yml
          name: deployments
          path: packages/contracts/deployments 
      - name: Build
        run: yarn dapp:build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./packages/dapp/build

  deploy:
    name: Deploy dapp
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./packages/dapp/build
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

