name: ci
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-18.04
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --prod
      - name: Compile contract
        run: yarn contracts:compile token.ligo
      - name: Deploy contract
        run: yarn contracts:deploy testnet
      - name: Build Dapp
        run: yarn dapp:build
        env:
          REACT_APP_RPC: "https://testnet-tezos.giganode.io"
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./packages/dapp/build

  deploy:
    name: Deploy dapp
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./packages/dapp/build
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

